version: "3"

tasks:

  app_migrations:
    aliases: 
      - gen
    desc: "Something funny idk"
    cmds: 
      - 

  tast_migrations:
    aliases: 
      - gen
    desc: "Something funny idk"
    cmds: 
      - 

  run_app: 
    aliases: 
      - gen
    desc: "Something funny idk"
    cmds: 
      - go run cmd/url-shortener/main.go --config=./config/config.yaml